### ISSUE TITLE
Set PC from cmd args

### ISSUE THREAD

**Issue by matmuher** [Karpov-Ruslan/RISCV-Simulator#14]
It would be convenient to support next cmd arg:
./Simulator --pc 765

**Comment by matmuher** [comment]
Also it would be nice to support "-d" flag, that will trigger execution of program stopping after execution of each instruction.
Just like gdb works. For simulator, it should be able to print current state (PC, registers - Hart::Dump())

**Comment by Karpov-Ruslan** [comment]
> It would be convenient to support next cmd arg: ./Simulator --pc 765

Done
