### ISSUE TITLE
Add cmd args to create_ram.py script

### ISSUE THREAD

**Issue by matmuher** [Karpov-Ruslan/RISCV-Simulator#15]
Next case is desired:
python create_ram.py 8-queens.bin

**Comment by matmuher** [comment]
May be it will become unnecessary when we move to mmap() ram allocation.
In this case the same functionality will be needed in simulator app

**Comment by Karpov-Ruslan** [comment]
If you want to add `mmap()` RAM allocation, please, don't remove file RAM allocation.

**Comment by matmuher** [comment]
Okey

**Comment by matmuher** [comment]
Done
